### ISSUE TITLE
Use packed fields

### ISSUE THREAD

**Issue by karenzshea** [mapbox/the-alchemist#2]
Schema currently looks like

```
abc
abc
abc
...
```

What about using packed fields like

```
aaa    |
bbb    | --- all one message
ccc    |
...
aaa
bbb
ccc
```

**Comment by daniel-j-h** [comment]
:+1: this should bring the file size down by a lot.

I think at the moment there are not really any savings compared to the raw csv (?)

**Comment by karenzshea** [comment]
This is done!
